<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Create new, delete and change role of existing users.' => 'Stwórz, usuń lub zmień uprawnienia istniejących użytkowników.',
    'Define new and remove old device types.' => 'Zdefiniuj nowe lub usuń istniejące typy urządzeń.',
    'Define new, edit and remove planes.' => 'Zdefiniuj nowe, edytuj lub usuń istniejące mapy.',
    'Device type management' => 'Zarządzanie zdefiniowanymi typami urządzeń',
    'Planes management' => 'Zarządzanie mapami',
    'User management' => 'Zarządzanie użytkownikami',
    'Welcome back {username}!' => 'Witaj ponownie {username}!',
    'What would you like to do?' => 'Co chciałbyś zrobić?',
    '{icon} Create new plane' => '{icon} Zdefiniuj nową mapę',
    '{icon} Create new type of device' => '{icon} Zdefiniuj nowy typ urządzenia',
    '{icon} Create new user' => '{icon} Utwórz nowego użytkownika',
    '{icon} Device type list' => '{icon} Lista typów urządzeń',
    '{icon} Planes list' => '{icon} Lista map',
    '{icon} User list' => '{icon} Lista użytkowników',
];
