<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '{plane}' => '',
    'Choose map.' => 'Wybierz mapę.',
    'Choose plane' => 'Wybierz mapę',
    'Create new' => 'Utwórz nowy',
    'Delete' => 'Usuń',
    'Edit' => 'Edytuj',
    'Error while processing operation.' => 'Błąd podczas przetwarzania operacji.',
    'Group' => 'Grupa',
    'Operation completed successfuly.' => 'Operacja zakończona sukcesem.',
    'Please choose plane, selected plane will be set as default for further use.' => 'Proszę wybrać mapę, wybrana mapa będzie używana w przyszłości jako domyślna.',
    'You don\'t have sufficient privileges to perform this action.' => 'Nie masz wystarczających uprawnień aby wykonać tą akcję.',
];
