<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Assigned permissions' => 'Uprawnienia użytkownika',
    'Assigned roles' => 'Przydzielone role',
    'Change password' => 'Zmień hasło',
    'Current language' => 'Aktualny język',
    'Email' => 'Email',
    'Here are your account details.' => 'Szczegóły twojego konta.',
    'Password' => 'Hasło',
    'Profile details' => 'Szczegóły konta',
    'Settings' => 'Ustawienia',
    'Usefull links' => 'Przydatne linki',
    'Username' => 'Użytkownik',
];
