<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Cannot delete group {name}. Group has elements that still are connected.' => 'Nie można usunąć grupy {name}. Grupa zawiera elementy, które są wciąż podłączone.',
    'Cannot delete group {name}. Group has sub-groups.' => 'Nie można usunąć grupy {name}. Grupa ma podgrupy.',
    '{name} deleted successfuly.' => '{name} usunięta z sukcesem.',
];
