<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Connection' => 'Połączenie',
    'Connection in from' => 'Połączenie do z',
    'Connection out to' => 'Połączenie z do',
    'Delete' => 'Usuń',
    'Description' => 'Opis',
    'Do you really want to delete this connection? Operation is not reversible.' => 'Czy na pewno chcesz usunąć to połączenie? Operacja jest nieodwracalna.',
    'Edit' => 'Edytuj',
    'Link in from {object}' => 'Połączenie do z {object}',
    'Link out to {object}' => 'Połączenie z do {object}',
    'Not set.' => 'Nie ustawiono.',
    'Save' => 'Zapisz',
    'Search for element ...' => 'Wyszukaj element...',
    'Waiting for results...' => 'Oczekiwanie na wyniki...',
];
