<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'An error occured while deleting element.' => 'Wystąpił błąd podczas usuwania elementu.',
    'An error occured while deleting group.' => 'Wystąpił błąd podczas usuwania urządzenia.',
    'Bad parent.' => 'Nieprawidłowe urządzenie nadrzędne.',
    'Bad position.' => 'Nieprawidłowa pozycja.',
    'Cannot delete element {name}. Something is still connected to it.' => '',
    'Edit' => 'Edytuj',
    'Error. Parent not exist.' => 'Błąd. Grupa nadrzędna nie istnieje.',
    'Group Id' => 'ID Urządzenia',
    'Group description' => 'Opis urządzenia',
    'Group name' => 'Nazwa urządzenia',
    'No parent set.' => 'Brak ustawionego urządzenia nadrzędnego',
    'Parent group' => 'Urządzenie nadrzędne',
    'Parent not set.' => 'Urządzenie nadrzędne nie ustawiona.',
    'Position on map' => 'Pozycja na mapie',
    'Save new' => 'Zapisz',
    'Type' => 'Typ',
    '{name} deleted successfuly.' => '{name} usunięte z powodzeniem.',
];
