<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Create new, delete and change role of existing users.' => '',
    'Define new and remove old device types.' => '',
    'Define new, edit and remove planes.' => '',
    'Device type management' => '',
    'Planes management' => '',
    'User management' => '',
    'Welcome back {username}!' => '',
    'What would you like to do?' => '',
    '{icon} Create new plane' => '',
    '{icon} Create new type of device' => '',
    '{icon} Create new user' => '',
    '{icon} Device type list' => '',
    '{icon} Planes list' => '',
    '{icon} User list' => '',
];
