<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About project' => '',
    'Application is licensed under MIT License if not stated otherwise. For more informations please check  <i>license.md</i> file in root directory of the application.' => '',
    'I would like to thank Yii Developers Team and Yii Community for creating Yii2 framework and all the extensions that could be used here. Without you this could not be created.' => '',
    'Project you are now seeing was created as a part of obtaining my engineer degree. Application was developed by Piotr "Proenix" Trzepacz during the period of one and half year and hopefully will be maintained and further extended in next few years.' => '',
    'See the project page on {url}' => '',
];
